# Generated by Django 4.1.7 on 2023-03-24 04:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, default='images/default_user_image.jpg', upload_to='images')),
                ('bio', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chez',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('recipe', models.CharField(max_length=1000)),
                ('image', models.ImageField(default='images/default_chez_image.jpg', upload_to='images')),
                ('is_published', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logged_in_chef', to='chezapi.chef')),
                ('chefscribed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chefavorites', to='chezapi.chef')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('like', models.BooleanField(blank=True, null=True)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likers', to='chezapi.chef')),
                ('chez', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_chezzes', to='chezapi.chez')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=150)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chezapi.chef')),
                ('chez', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chez_comments', to='chezapi.chez')),
            ],
        ),
        migrations.CreateModel(
            name='ChezCheese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheese', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheeses', to='chezapi.cheese')),
                ('chez', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chezzes', to='chezapi.chez')),
            ],
        ),
        migrations.AddField(
            model_name='chez',
            name='cheeses',
            field=models.ManyToManyField(through='chezapi.ChezCheese', to='chezapi.cheese'),
        ),
        migrations.AddField(
            model_name='chez',
            name='chef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chezapi.chef'),
        ),
        migrations.AddField(
            model_name='chef',
            name='subscriptions',
            field=models.ManyToManyField(through='chezapi.Subscribe', to='chezapi.chef'),
        ),
        migrations.AddField(
            model_name='chef',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('body', models.CharField(max_length=5000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='chezapi.chef')),
            ],
        ),
    ]
