# Generated by Django 4.1.7 on 2023-03-11 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chezapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='chez',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chez_comments', to='chezapi.chez'),
        ),
    ]
