# Generated by Django 4.1.7 on 2023-03-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chezapi', '0002_alter_comment_chez'),
    ]

    operations = [
        migrations.AddField(
            model_name='chez',
            name='cheeses',
            field=models.ManyToManyField(through='chezapi.ChezCheese', to='chezapi.cheese'),
        ),
    ]
