# Generated by Django 4.1.7 on 2023-03-15 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chezapi', '0005_alter_chez_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='chef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='chezapi.chef'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chefavorites', to='chezapi.chef'),
        ),
    ]
